#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif
/*
#ifndef LV_ATTRIBUTE_LARGE_CONST
#define LV_ATTRIBUTE_LARGE_CONST
#endif
*/ 

/*------------------------------------------------------------------
 * MACROS FOR IMAGE ATTRIBUTES ACCORDING TO FRAME AND ORIENTATION
 *------------------------------------------------------------------*/
/* PENGUIN SIT1 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT1
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT1
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT1_90
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT1_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT1_180
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT1_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT1_270
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT1_270
#endif

/* PENGUIN SIT2 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT2
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT2
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT2_90
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT2_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT2_180
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT2_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SIT2_270
#define LV_ATTRIBUTE_IMG_PENGUIN_SIT2_270
#endif

/* PENGUIN WALK1 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK1
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK1
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK1_90
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK1_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK1_180
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK1_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK1_270
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK1_270
#endif

/* PENGUIN WALK2 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK2
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK2
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK2_90
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK2_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK2_180
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK2_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_WALK2_270
#define LV_ATTRIBUTE_IMG_PENGUIN_WALK2_270
#endif

/* PENGUIN RUN1 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN1
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN1
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN1_90
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN1_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN1_180
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN1_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN1_270
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN1_270
#endif

/* PENGUIN RUN2 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN2
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN2
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN2_90
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN2_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN2_180
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN2_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_RUN2_270
#define LV_ATTRIBUTE_IMG_PENGUIN_RUN2_270
#endif

/* PENGUIN BARK1 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK1
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK1
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK1_90
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK1_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK1_180
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK1_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK1_270
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK1_270
#endif

/* PENGUIN BARK2 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK2
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK2
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK2_90
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK2_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK2_180
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK2_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_BARK2_270
#define LV_ATTRIBUTE_IMG_PENGUIN_BARK2_270
#endif

/* PENGUIN SNEAK1 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1_90
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1_180
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1_270
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK1_270
#endif

/* PENGUIN SNEAK2 */
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2_90
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2_90
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2_180
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2_180
#endif
#ifndef LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2_270
#define LV_ATTRIBUTE_IMG_PENGUIN_SNEAK2_270
#endif

/*------------------------------------------------------------------
 * IMAGE MAPS (BYTE ARRAYS)
 * Four versions are defined for each frame:
 *   - Orientation 180: resolution 32x24px
 *   - Orientations 0, 90 y 270: resolution 24x32px
 *   - CONFIG_NICE_OLED_WIDGET_LUNA_VERTICAL_READ for QMK!!
 *   - CONFIG_NICE_OLED_WIDGET_LUNA_HORIZONTAL_READ for ZMK!!!
 *------------------------------------------------------------------*/
